name: release container image
on:
  push:
    tags:
      - "*"

permissions:
  packages: write

jobs:
  goreleaser:
    name: build and push zippy container and chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Release container image to Github
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Push zippy helm chart
      #   uses: appany/helm-oci-chart-releaser@v0.3.0
      #   with:
      #     name: zippy
      #     repository: jarededwards
      #     tag: ${{ github.ref_name }}
      #     path: charts/zippy-chart # Default charts/{name}
      #     registry: ghcr.io
      #     registry_username: ${{ github.actor }}
      #     registry_password: ${{ secrets.GITHUB_TOKEN }}
      #     # update_dependencies: 'true' # Defaults to false
